# -*- coding: utf-8 -*-
"""day14_ex02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OCFbILzO6RX8uuo-DSPKS-NLmqk2o67S

### SQLite3 - DataBase
"""


"""
from google.colab import drive
drive.mount('/content/gdrive/')
"""
import sqlite3 as s

conn = s.connect('/Users/gaegul/PycharmProjects/pythonProject/test.db')
c = conn.cursor()


c.execute('drop table if exists MenuPan2')
c.execute('create table MenuPan2(menuName char(50), price int)')
c.execute('insert into menupan2 values("김밥", 3000) ')
c.execute('insert into menupan2 values("순두부", 6000) ')
c.execute('insert into menupan2 values("육개장", 7500) ')
c.execute('insert into menupan2 values("칼국수", 5500) ')
c.execute('insert into menupan2 values("자짱밥", 5500) ')
c.execute('insert into menupan2 values("김치찌게", 8000) ')


conn.commit()

c.execute('select * from MenuPan2')
rows = c.fetchall()

for row in rows:
    print('{} {}'.format(row[0], row[1]))



c.close()
conn.close()
